services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "4200:4200"
    volumes:
      - ./src:/subvision/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
